### PR TITLE
Blog card CSS fix

### PR DESCRIPTION
**Pull request by cxjay26**
Fixed CSS for recent blog posts cards where the titles were not the same size.

### CODE REVIEW

**Comment by cxjay26** [comment]
Please review most recent changes. I believe I did this correctly in SCSS.

**Comment by jferragut** [comment]
@cxjay26 looks like the latest deploy preview failed due to an extra bracket. Here is a screenshot
Screen Shot 2019-10-24 at 12 38 45 PM

**Comment by cxjay26** [comment]
Should be good now

**Comment by jferragut** [comment]
Fixes issue #54

**Pull request merged**
